namespaceOverride: amprion-policies

# Tests configuration
test:
  image:
    # -- (string) Image registry
    registry: jpd-edge1.amp-cloud.lan/dockerhub-docker-sremote

# Cleanup cronjobs to prevent internal resources from stacking up in the cluster
cleanupJobs:
  admissionReports:
    image:
      # -- (string) Image registry
      registry: jpd-edge1.amp-cloud.lan/dockerhub-docker-sremote
  clusterAdmissionReports:
    image:
      # -- (string) Image registry
      registry: jpd-edge1.amp-cloud.lan/dockerhub-docker-sremote

# Admission controller configuration
admissionController:
  replicas: 3
  initContainer:
    image:
      # -- Image registry
      registry: jpd-edge1.amp-cloud.lan/github-docker-sremote
  container:
    image:
      # -- Image registry
      registry: jpd-edge1.amp-cloud.lan/github-docker-sremote

# Background controller configuration
backgroundController:
  image:
    # -- Image registry
    registry: jpd-edge1.amp-cloud.lan/github-docker-sremote

# Cleanup controller configuration
cleanupController:
  image:
    # -- Image registry
    registry: jpd-edge1.amp-cloud.lan/github-docker-sremote

# Reports controller configuration
reportsController:
  image:
    # -- Image registry
    registry: jpd-edge1.amp-cloud.lan/github-docker-sremote

# CRDs configuration
crds:
  # -- Whether to have Helm install the Kyverno CRDs, if the CRDs are not installed by Helm, they must be added before policies can be created
  install: true
  migration:
    # -- Enable CRDs migration using helm post upgrade hook
    enabled: true
    image:
      # -- (string) Image registry
      registry: jpd-edge1.amp-cloud.lan/github-docker-sremote
      # -- (string) Image repository
      repository: kyverno/kyverno-cli